version: '3.9'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile.spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
